### ISSUE TITLE
Downloading files outside of project working directory

### ISSUE THREAD

**Issue by sg-peytrignet** [HFAnalyticsLab/monstR#46]
Hello,

I seem to have an issue with the monstr_pipeline_defaults() function. If I don't specify any options, it runs smoothly and the ONS datasets are saved in a folder called /data in my R project directory. If I specify a different download_root (because, say, I would like the files to be saved outside of the project) then the code below breaks.

Any ideas what may be causing this?

Many thanks.

``` r
library(monstR)

data_location <- "M:/Analytics/Networked Data Lab"

setwd(data_location)

monstr_pipeline_defaults(download_root=data_location) %>%
ons_datasets_setup() %>%
ons_dataset_by_id(id="mid-year-pop-est",edition="mid-2019-april-2020-geography",version=1)  %>%
  ons_download(format="csv") %>%
  monstr_read_file() %>%  
  monstr_clean() %>%
  monstr_write_clean(format="all")
#> INFO [2020-08-24 13:40:02] Version 1 of mid-2019-april-2020-geography edition selected
#> INFO [2020-08-24 13:40:02] Retrieving dataset metadata from https://api.beta.ons.gov.uk/v1/datasets/mid-year-pop-est/editions/mid-2019-april-2020-geography/versions/1
#> INFO [2020-08-24 13:40:02] Downloading data from https://download.beta.ons.gov.uk/downloads/datasets/mid-year-pop-est/editions/mid-2019-april-2020-geography/versions/1.csv
#> INFO [2020-08-24 13:40:07] File created at /data/raw/ons/mid-year-pop-est/mid-2019-april-2020-geography/mid-year-pop-est-v1.csv
#> Parsed with column specification:
#> cols(
#>   v4_0 = col_double(),
#>   `calendar-years` = col_double(),
#>   time = col_double(),
#>   `admin-geography` = col_character(),
#>   geography = col_character(),
#>   `mid-year-pop-sex` = col_double(),
#>   sex = col_character(),
#>   `mid-year-pop-age` = col_character(),
#>   age = col_character()
#> )
#> INFO [2020-08-24 13:40:10] Writing csv data to /data/clean/ons/mid-year-pop-est/mid-2019-april-2020-geography/mid-year-pop-est-v1.csv
#> INFO [2020-08-24 13:41:19] Writing xlsx data to /data/clean/ons/mid-year-pop-est/mid-2019-april-2020-geography/mid-year-pop-est-v1.xlsx
#> ERROR [2020-08-24 13:41:33] Problem writing xlsx
#> INFO [2020-08-24 13:41:33] Writing rds data to /data/clean/ons/mid-year-pop-est/mid-2019-april-2020-geography/mid-year-pop-est-v1.rds
#> [1] TRUE
```

<sup>Created on 2020-08-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by emmavestesson** [comment]
Hi Seb, 

Very strange. It looks like the raw and cleaned csvs are saved, but the cleaned xlsx is the problem. is that correct?

**Comment by sg-peytrignet** [comment]
Hi Emma - none of the files are being written in my local folder "data_location", perhaps I'm specifying the download location in the wrong function?

**Comment by hr283** [comment]
I am having a similar issue, having just installed the monstr package from github today. My R version is 3.6.1

My code is almost exactly the same as the example above (except with a different path for the data location), but I get a slightly different error. Unfortunately I can't copy and paste it because the error is fatal and my R studio session aborts. In summary it is:

```
INFO [datetime] Version 1 of mid-2019-april-2020-geography edition selected
INFO [datetime] Retreiving dataset metadata from...
INFO [datetime] Downloading data from ...
INFO [datetime] Creating directory /data/raw/ons/mid-year-pop-est/mid-2019-april-2020-geography
ERROR [datetime] file /data/raw/ons/mid-year-pop-est/mid-2019-april-2020-geography/mid-year-pop-est-v1.csv Not created!
```

My R session also aborts if I don't attempt to set the download_root. Any ideas what is going wrong?

Thanks,
Hannah

**Comment by emmavestesson** [comment]
Hi @hr283 , 

Thanks for flagging this. I found the problem and I've fixed it. Could you reinstall from github and try again, please? Let me know if you have any issues and thanks for using monstR!

**Comment by hr283** [comment]
Hi Emma,

Thanks very much for your help. I'm still having issues, but have narrowed them down to when I try to set a path to a folder on a Network drive as the download_root. I am wondering if this is because the Network drive location has an `&` in the path - something I unfortunately can't change! It seems to be being converted to `&amp;` in the error message (the error message is the same as the one in my previous post, but with a different folder path).

For now I'll use a local directory as the download_root and move the data onto the Network drive once I've finished with monstR.

Is there any way of stopping R from attempting to abort the session when these sorts of errors are encountered?

Thanks,

Hannah
